version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:

#https://docs.docker.com/compose/
#https://dev.to/ingresse/docker-e-docker-compose-um-guia-para-iniciantes-48k8